version: '3'

services:

    nginx:
        image: nginx:1.17
        ports:
            - 8000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - app-volume:/app
        depends_on:
            - app
            - mongo
        networks:
            - test

    app:
        image: mrsuh/rent-view
        depends_on:
            - mongo
        environment:
            LISTEN_HOST: 0.0.0.0
            LISTEN_PORT: 9070
            DATABASE_URL: 'mongodb://mongo/rent-collector'

        ports:
            - 9070
        networks:
            - test
        volumes:
            - app-volume:/app

    mongo:
        image: mongo:3.4
        restart: always
        networks:
            - test

    mongosetup:
        image: mongo:3.4
        volumes:
            - ./dump:/dump
        entrypoint: ["mongorestore", "--host", "mongo", "--db", "rent-collector", "--dir", "/dump", "--drop"]
        networks:
            - test

networks:
    test: ~

volumes:
    app-volume: